In [351]:
import pandas as pd
import numpy as np

In [3]:
mushroom_path = './mushroom.csv'

In [4]:
mushroom = pd.read_csv(mushroom_path)

In [5]:
mushroom

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
5        e         x           y         y       t    a               f   
6        e         b           s         w       t    a               f   
7        e         b           y         w       t    l               f   
8        p         x           y         w       t    p               f   
9        e         b           s         y       t    a               f   
10       e         x           y         y       t    l               f   
11       e         x           y         y       t    a               f   
12       e         b           s         y       t    a               f   
13       p         x           y         w       t    p               f   
14       e         x           f         n       f    n               f   
15       e         s           f         g       f    n               f   
16       e         f           f         w       f    n               f   
17       p         x           s         n       t    p               f   
18       p         x           y         w       t    p               f   
19       p         x           s         n       t    p               f   
20       e         b           s         y       t    a               f   
21       p         x           y         n       t    p               f   
22       e         b           y         y       t    l               f   
23       e         b           y         w       t    a               f   
24       e         b           s         w       t    l               f   
25       p         f           s         w       t    p               f   
26       e         x           y         y       t    a               f   
27       e         x           y         w       t    l               f   
28       e         f           f         n       f    n               f   
29       e         x           s         y       t    a               f   
...    ...       ...         ...       ...     ...  ...             ...   
8094     e         b           s         g       f    n               f   
8095     p         x           y         c       f    m               f   
8096     e         k           f         w       f    n               f   
8097     p         k           y         n       f    s               f   
8098     p         k           s         e       f    y               f   
8099     e         k           f         w       f    n               f   
8100     e         f           s         n       f    n               a   
8101     p         k           s         e       f    s               f   
8102     e         x           s         n       f    n               a   
8103     e         k           s         n       f    n               a   
8104     e         k           s         n       f    n               a   
8105     e         k           s         n       f    n               a   
8106     e         k           s         n       f    n               a   
8107     e         x           s         n       f    n               a   
8108     p         k           y         e       f    y               f   
8109     e         b           s         w       f    n               f   
8110     e         x           s         n       f    n               a   
8111     e         k           s         w       f    n               f   
8112     e         k           s         n       f    n               a   
8113     p         k           y         e       f    y               f   
8114     p         f           y         c       f    m               a   
8115     e         x          

In [86]:
mushroom.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-adove-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [6]:
mushroom.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-adove-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 22 columns]

In [7]:
mushroom.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-adove-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [150]:
mushroom_x = mushroom[['class','cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-surface-below-ring','stalk-color-adove-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']]

In [151]:
mushroom_x = mushroom.drop(columns = 'class')

In [152]:
mushroom_y = mushroom['class']

In [153]:
from sklearn.tree import DecisionTreeClassifier

In [96]:
decision = DecisionTreeClassifier('entropy')

In [154]:
decision

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [156]:
decision.fit(mushroom_x, mushroom_y)

ValueError: could not convert string to float: 'x'

In [158]:
mushroom_x = pd.get_dummies(mushroom_x)

In [159]:
mushroom_x

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               1            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
5               0            0            0            0            0   
6               1            0            0            0            0   
7               1            0            0            0            0   
8               0            0            0            0            0   
9               1            0            0            0            0   
10              0            0            0            0            0   
11              0            0            0            0            0   
12              1            0            0            0            0   
13              0            0            0            0            0   
14              0            0            0            0            0   
15              0            0            0            0            1   
16              0            0            1            0            0   
17              0            0            0            0            0   
18              0            0            0            0            0   
19              0            0            0            0            0   
20              1            0            0            0            0   
21              0            0            0            0            0   
22              1            0            0            0            0   
23              1            0            0            0            0   
24              1            0            0            0            0   
25              0            0            1            0            0   
26              0            0            0            0            0   
27              0            0            0            0            0   
28              0            0            1            0            0   
29              0            0            0            0            0   
...           ...          ...          ...          ...          ...   
8094            1            0            0            0            0   
8095            0            0            0            0            0   
8096            0            0            0            1            0   
8097            0            0            0            1            0   
8098            0            0            0            1            0   
8099            0            0            0            1            0   
8100            0            0            1            0            0   
8101            0            0            0            1            0   
8102            0            0            0            0            0   
8103            0            0            0            1            0   
8104            0            0            0            1            0   
8105            0            0            0            1            0   
8106            0            0            0            1            0   
8107            0            0            0            0            0   
8108            0            0            0            1            0   
8109            1            0            0            0            0   
8110            0            0            0            0            0   
8111            0            0            0            1            0   
8112            0            0            0            1            0   
8113            0            0            0            1            0   
8114            0            0            1            0            0   
8115            0            0            0            0            0   
8116            0            0            0            1        

In [161]:
decision.fit(mushroom_x, mushroom_y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [162]:
decision.score(mushroom_x,mushroom_y)

1.0

In [224]:
decision.classes_

array(['e', 'p'], dtype=object)

In [164]:
from sklearn.tree import export_graphviz, plot_tree

In [165]:
print(export_graphviz(decision))

digraph Tree {
node [shape=box] ;
0 [label="X[27] <= 0.5\nentropy = 0.999\nsamples = 8124\nvalue = [4208, 3916]"] ;
1 [label="X[20] <= 0.5\nentropy = 0.667\nsamples = 4596\nvalue = [800, 3796]"] ;
0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;
2 [label="X[91] <= 0.5\nentropy = 0.974\nsamples = 1344\nvalue = [800, 544]"] ;
1 -> 2 ;
3 [label="X[28] <= 0.5\nentropy = 0.799\nsamples = 1056\nvalue = [800, 256]"] ;
2 -> 3 ;
4 [label="entropy = 0.0\nsamples = 800\nvalue = [800, 0]"] ;
3 -> 4 ;
5 [label="entropy = 0.0\nsamples = 256\nvalue = [0, 256]"] ;
3 -> 5 ;
6 [label="entropy = 0.0\nsamples = 288\nvalue = [0, 288]"] ;
2 -> 6 ;
7 [label="entropy = 0.0\nsamples = 3252\nvalue = [0, 3252]"] ;
1 -> 7 ;
8 [label="X[95] <= 0.5\nentropy = 0.214\nsamples = 3528\nvalue = [3408, 120]"] ;
0 -> 8 [labeldistance=2.5, labelangle=-45, headlabel="False"] ;
9 [label="X[58] <= 0.5\nentropy = 0.106\nsamples = 3456\nvalue = [3408, 48]"] ;
8 -> 9 ;
10 [label="X[7] <= 0.5\nentropy = 0.024\nsample

In [242]:
from sklearn.linear_model import LogisticRegression

In [243]:
lr = LogisticRegression()

In [244]:
lr.fit(mushroom_x,mushroom_y)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [245]:
lr.coef_

array([[ 2.67728825e-01,  5.29563092e-01,  3.96625556e-02,
        -3.07666182e-02, -5.66808792e-01, -8.30172746e-02,
        -7.15404561e-01,  7.94655477e-01,  1.59053350e-01,
        -8.19424784e-02,  1.05199565e+00, -7.39804327e-01,
        -1.67798264e-03,  1.25280491e-01, -4.32029939e-01,
         1.02761549e+00, -4.93937727e-01, -4.93937727e-01,
         4.80108905e-01, -3.67251044e-01, -4.51826606e-01,
         6.08188394e-01, -3.50724881e+00,  3.67032325e+00,
         3.57730608e+00, -3.50724881e+00,  3.55846442e-01,
        -4.08363408e+00,  2.06491339e+00,  7.93052168e-01,
         7.93052168e-01, -2.21518453e-01,  3.77880241e-01,
         1.14881725e+00, -9.92455461e-01, -2.17954759e+00,
         2.33590938e+00,  1.62522048e+00, -6.10886672e-01,
         1.76946109e-02,  1.60484224e-01, -5.24677122e-01,
        -6.12447634e-01, -1.50971403e-01, -3.72110798e-01,
         8.03928316e-01, -1.53720252e-01, -1.67642715e-01,
         1.41490755e-01,  5.00303329e-01, -3.43941541e-0

In [246]:
lr.classes_

array(['e', 'p'], dtype=object)

In [247]:
mushroom_x.dtypes

cap-shape_b            uint8
cap-shape_c            uint8
cap-shape_f            uint8
cap-shape_k            uint8
cap-shape_s            uint8
cap-shape_x            uint8
cap-surface_f          uint8
cap-surface_g          uint8
cap-surface_s          uint8
cap-surface_y          uint8
cap-color_b            uint8
cap-color_c            uint8
cap-color_e            uint8
cap-color_g            uint8
cap-color_n            uint8
cap-color_p            uint8
cap-color_r            uint8
cap-color_u            uint8
cap-color_w            uint8
cap-color_y            uint8
bruises_f              uint8
bruises_t              uint8
odor_a                 uint8
odor_c                 uint8
odor_f                 uint8
odor_l                 uint8
odor_m                 uint8
odor_n                 uint8
odor_p                 uint8
odor_s                 uint8
                       ...  
ring-number_n          uint8
ring-number_o          uint8
ring-number_t          uint8
ring-type_e   

In [248]:
lr.score(mushroom_x, mushroom_y)

1.0

In [249]:
from sklearn.neural_network import MLPClassifier

In [175]:
mlp = MLPClassifier((20,),activation='logistic')

In [176]:
mlp.fit(mushroom_x,mushroom_y)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(20,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [177]:
mlp.score(mushroom_x, mushroom_y)

1.0

# Cross Validation (mushroom)

In [476]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

In [477]:
kfold = KFold(n_splits=7)

In [478]:
cross_val_score(DecisionTreeClassifier(), mushroom_x, mushroom_y, cv=kfold)

array([1.       , 1.       , 1.       , 1.       , 1.       , 1.       ,
       0.9862069])

In [479]:
cross_val_score(LogisticRegression(), mushroom_x, mushroom_y, cv=kfold)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework

array([0.99655469, 1.        , 1.        , 1.        , 0.99396552,
       1.        , 1.        ])

In [480]:
cross_val_score(DecisionTreeClassifier(), wine_x, wine_y, cv=kfold)

array([0.4058127 , 0.38038793, 0.45689655, 0.42672414, 0.40301724,
       0.46659483, 0.44719828])

In [481]:
cross_val_score(LogisticRegression(),wine_x, wine_y, cv=kfold)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.


array([0.4510226 , 0.47737069, 0.51400862, 0.50215517, 0.59698276,
       0.55711207, 0.57974138])

# NUMERIC DATA 

In [395]:
wine_path = './winequalityN.csv'

In [396]:
wine = pd.read_csv(wine_path)

In [397]:
wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000   
mean      0.056042            30.525319            115.744574     0.994697   
std       0.035036            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6488.000000  6493.000000  6497.000000  6497.000000  
mean      3.218395     0.531215    10.491801     5.818378  
std       0.160748     0.148814     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [461]:
wine_x = wine.drop(columns = ['type','quality'])

In [462]:
wine_y = wine['quality']

In [463]:
decision_wine = DecisionTreeClassifier('entropy')

In [464]:
wine_x.fillna(wine_x.mean(), inplace=True)

In [465]:
wine_x = wine_x.fillna(wine_x.mean())


In [466]:
wine_x._is_view

False

In [467]:
decision_wine.fit(wine_x, wine_y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [468]:
decision_wine.classes_

array([3, 4, 5, 6, 7, 8, 9])

In [469]:
print(export_graphviz(decision_wine))

digraph Tree {
node [shape=box] ;
0 [label="X[10] <= 10.625\nentropy = 1.838\nsamples = 6497\nvalue = [30, 216, 2138, 2836, 1079, 193, 5]"] ;
1 [label="X[1] <= 0.237\nentropy = 1.596\nsamples = 3866\nvalue = [19, 154, 1801, 1586, 270, 35, 1]"] ;
0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;
2 [label="X[10] <= 8.95\nentropy = 1.655\nsamples = 1055\nvalue = [4, 21, 250, 592, 160, 28, 0]"] ;
1 -> 2 ;
3 [label="X[0] <= 7.25\nentropy = 1.943\nsamples = 121\nvalue = [1, 0, 35, 47, 20, 18, 0]"] ;
2 -> 3 ;
4 [label="X[8] <= 3.24\nentropy = 1.272\nsamples = 66\nvalue = [1, 0, 26, 37, 1, 1, 0]"] ;
3 -> 4 ;
5 [label="X[0] <= 6.85\nentropy = 0.882\nsamples = 40\nvalue = [0, 0, 8, 31, 0, 1, 0]"] ;
4 -> 5 ;
6 [label="X[3] <= 12.7\nentropy = 0.523\nsamples = 34\nvalue = [0, 0, 4, 30, 0, 0, 0]"] ;
5 -> 6 ;
7 [label="X[0] <= 6.45\nentropy = 0.991\nsamples = 9\nvalue = [0, 0, 4, 5, 0, 0, 0]"] ;
6 -> 7 ;
8 [label="X[4] <= 0.11\nentropy = 0.722\nsamples = 5\nvalue = [0, 0, 4, 1, 0, 0, 0]"]

In [470]:
decision_wine.score(wine_x, wine_y)

1.0

In [475]:
wine

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36           20.70   
1     white            6.3             0.300         0.34            1.60   
2     white            8.1             0.280         0.40            6.90   
3     white            7.2             0.230         0.32            8.50   
4     white            7.2             0.230         0.32            8.50   
5     white            8.1             0.280         0.40            6.90   
6     white            6.2             0.320         0.16            7.00   
7     white            7.0             0.270         0.36           20.70   
8     white            6.3             0.300         0.34            1.60   
9     white            8.1             0.220         0.43            1.50   
10    white            8.1             0.270         0.41            1.45   
11    white            8.6             0.230         0.40            4.20   
12    white            7.9             0.180         0.37            1.20   
13    white            6.6             0.160         0.40            1.50   
14    white            8.3             0.420         0.62           19.25   
15    white            6.6             0.170         0.38            1.50   
16    white            6.3             0.480         0.04            1.10   
17    white            NaN             0.660         0.48            1.20   
18    white            7.4             0.340         0.42            1.10   
19    white            6.5             0.310         0.14            7.50   
20    white            6.2             0.660         0.48            1.20   
21    white            6.4             0.310         0.38            2.90   
22    white            6.8             0.260         0.42            1.70   
23    white            7.6             0.670         0.14            1.50   
24    white            6.6             0.270         0.41            1.30   
25    white            7.0             0.250         0.32            9.00   
26    white            6.9             0.240         0.35            1.00   
27    white            7.0             0.280         0.39            8.70   
28    white            7.4             0.270         0.48            1.10   
29    white            7.2             0.320         0.36            2.00   
...     ...            ...               ...          ...             ...   
6467    red            6.2             0.510         0.14            1.90   
6468    red            6.4             0.360         0.53            2.20   
6469    red            6.4             0.380         0.14            2.20   
6470    red            7.3             0.690         0.32            2.20   
6471    red            6.0             0.580         0.20            2.40   
6472    red            5.6             0.310         0.78           13.90   
6473    red            7.5             0.520         0.40            2.20   
6474    red            8.0             0.300         0.63            1.60   
6475    red            6.2             0.700         0.15            5.10   
6476    red            6.8             0.670         0.15            1.80   
6477    red            6.2             0.560         0.09            1.70   
6478    red            7.4             0.350         0.33            2.40   
6479    red            6.2             0.560         0.09            1.70   
6480    red            6.1             0.715         0.10            2.60   
6481    red            6.2             0.460         0.29            2.10   
6482    red            6.7             0.320         0.44            2.40   
6483    red            7.2             0.390         0.44            2.60   
6484    red            7.5             0.310         0.41            2.40   
6485    red            5.8             0.610         0.11            1.80   
6486    red            7.2               NaN         0.33            2.50   
648

In [471]:
lr_wine = LogisticRegression()

In [472]:
lr_wine.fit(wine_x, wine_y)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [473]:
lr_wine.score(wine_x, wine_y)

0.5382484223487763

In [474]:
lr_wine.coef_

array([[ 2.47377265e-01,  2.42727926e+00, -6.98119802e-01,
        -5.57018866e-02,  2.69625842e-01,  2.83460188e-02,
        -2.20636168e-03, -6.45435018e-01, -7.06278402e-01,
        -1.14532222e+00, -4.03558713e-01],
       [-6.12385459e-02,  2.61179257e+00, -1.15062901e-01,
        -5.33671470e-02, -4.83611674e-01, -5.97769801e-02,
         1.03962235e-02,  3.82434624e-01, -5.37492211e-02,
        -1.95480663e+00, -2.73833800e-01],
       [ 4.12050549e-02,  3.00970297e+00,  3.28268475e-01,
        -4.84045343e-02,  1.15212664e+00, -1.06430097e-02,
         6.18330761e-03,  3.21398308e+00,  2.76321229e-01,
        -1.30191281e+00, -8.73452127e-01],
       [ 5.54481409e-03, -2.22910815e+00, -3.75356704e-01,
         2.39089913e-02,  1.60314630e-01,  5.41118619e-03,
        -3.74300697e-03, -5.79214602e-01,  1.62716865e-01,
         4.67661033e-01,  1.08414344e-01],
       [ 1.13817510e-02, -3.58814530e+00, -2.66761859e-01,
         3.63939978e-02, -1.86368044e+00,  8.76626181e-03,
  